---
name: security_scan
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'security scan'
        required: true
        default: full_scan
        type: choice
        options:
          - full_scan
          - internal scan
          - external scan

jobs:
  external_scan:
    runs-on: ubuntu-latest
    if: >
     github.event_name == 'schedule' ||
     github.event.inputs.scan_type == 'external scan' ||
      github.event.inputs.scan_type == 'full_scan'
    steps:
      - name: nmap scan
        run: sudo apt-get update && sudo apt-get install nmap -y
      - run: mkdir -p external_scans
      - run: |
          nmap -p- -sV -T4 ${{ secrets.SERVER_IP }} -oN external_scans/nmap_scan.txt
      - name: nuclei scan
        uses: projectdiscovery/nuclei-action@v3
        with:
          target: ${{ secrets.SERVER_IP }}
          output: external_scans/nuclei_scan.txt
      - name: run httpx
        uses: projectdiscovery/httpx-action@main
        with:
          list: ${{ secrets.SERVER_IP }}
          flags: '-tech-detect -status-code -title -web-server'
          output: external_scans/httpx_scan.txt
        continue-on-error: true
      - name: whatweb scan
        run: |
          sudo apt update && sudo apt-get install whatweb -y
          target_url="http://${{ secrets.SERVER_IP }}:80"
          whatweb --log-brief=external_scans/whatweb_scan.txt $target_url "$target_url"
      - name: setting up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: move the files
        run: |
          today=$(date +"%Y-%m-%d")
          remote_dir="/opt/openclaw/workspace/security_reports/server_report/$today"
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            "${{ secrets.VPS_USER }}@${{ secrets.SERVER_IP }}" \
             "mkdir -p \"$remote_dir\""
          scp -r -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
          external_scans \
          ${{ secrets.VPS_USER }}@${{ secrets.SERVER_IP }}:$remote_dir
