---
name: security_scan
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'security scan'
        required: true
        default: full_scan
        type: choice
        options:
          - full_scan
          - internal scan
          - external scan

jobs:
  external_scan:
    runs-on: ubuntu-latest
    if: >
     github.event_name == 'schedule' ||
     github.event.inputs.scan_type == 'external scan' ||
      github.event.inputs.scan_type == 'full_scan'
    steps:
      - name: nmap scan
        run: sudo apt-get update && sudo apt-get install nmap -y
      - run: mkdir -p scan_results
      - run: |
          nmap -p- -sV -T4 ${{ secrets.SERVER_IP }} -oN scan_results/nmap_scan.txt
      - name: nuclei scan
        uses: projectdiscovery/nuclei-action@v3
        with:
          target: ${{ secrets.SERVER_IP }}
          output: scan_results/nuclei_scan.txt
      - name: run httpx
        uses: projectdiscovery/httpx-action@main
        with:
          target: ${{ secrets.SERVER_IP }}
          flags: '-tech-detect -status-code -title -web-server'
          output: scan_results/httpx_scan.txt
      - name: whatweb scan
        run: |
          sudo apt update && sudo apt-get install whatweb -y
          target_url="http://${{ secrets.SERVER_IP }}:80"
          whatweb --log-brief=scan_results/whatweb_scan.txt $target_url "target_url"

      - name: upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: external_scan_results
          path: scan_results
          retention-days: 5